TaskC/Models/AddTourModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TaskC.Models
{
    public class AddTourModel
    {
        [Required]
        public List<int> Categories { get; set; }
        public string Title { get; set; }
        public DateTime StartAt { get; set; }
        public DateTime EndAt { get; set; }
    }
}

TaskC/Models/CategoryAddModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TaskC.Models
{
    public class CategoryAddModel
    {
        [Required]
        public string Title { get; set; }
    }
}

TaskC/Models/ErrorViewModel.cs
using System;

namespace TaskC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskC/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using TaskC.BLL.Interfaces;
using TaskC.Models;

namespace TaskC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            return View("Add");
        }

        public async Task<IActionResult> Insert(CategoryAddModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _categoryService.InsertAsync(model.Title);
                if (result)
                {
                    return RedirectToAction("Index");
                }
            }
            throw new Exception("Model state is invalid");
        }
    }
}

TaskC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TaskC.Models;

namespace TaskC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TaskC/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TaskC.BLL.Interfaces;
using TaskC.Helpers;
using TaskC.Models;

namespace TaskC.Controllers
{
    public class TourController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ITourService _tourService;

        public TourController(ICategoryService categoryService, 
            ITourService tourService)
        {
            _categoryService = categoryService;
            _tourService = tourService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Add()
        {
            var categories = await _categoryService.AllAsync();
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTourModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.StartAt < model.EndAt && model.Categories.Count > 0)
                {
                    var modelDTO = Mapper.Mapping(model);
                    await _tourService.AddAsync(modelDTO);
                    return RedirectToAction("Get");
                }
                return new JsonResult(model);
            }
            return RedirectToAction("Add");
        }

        public async Task<IActionResult> Get(List<int> filters)
        {
            var categories = await _categoryService.AllAsync();
            ViewBag.Categories = categories;
            var tours = await _tourService.ToListAsync(filters);
            ViewBag.Filters = filters;
            return View("View", tours);
        }
    }
}

TaskC/Views/Category/Add.cshtml
@model TaskC.Models.CategoryAddModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>CategoryAddModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Insert">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TaskC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tour" asp-action="Add">Add Tour</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tour" asp-action="Get">Tour List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TaskC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TaskC/Views/Tour/Add.cshtml
@model TaskC.Models.AddTourModel

@{
    ViewData["Title"] = "Add";
    var categories = ViewBag.Categories as List<CategoryDTO>;
}

<h1>Add</h1>

<h4>AddTourModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartAt" class="control-label"></label>
                <input type="date" asp-for="StartAt" class="form-control" />
                <span asp-validation-for="StartAt" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EndAt" class="control-label"></label>
                <input type="date" asp-for="EndAt" class="form-control" />
                <span asp-validation-for="EndAt" class="text-danger"></span>
            </div>

            @foreach (var item in categories)
            {
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="categories" value="@item.Id" id="defaultCheck-@item.Id">
                    <label class="form-check-label" for="defaultCheck-@item.Id">
                        @item.Title
                    </label>
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskC/Views/Tour/View.cshtml
@model IEnumerable<TaskC.DAL.Entities.Tour>

@{
    ViewData["Title"] = "View";
    var categories = ViewBag.Categories as List<CategoryDTO>;
    var filters = ViewBag.Filters as List<int>;
}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form action="" method="get">
    @foreach (var item in categories)
    {
        <div class="form-check">
            <input class="form-check-input" type="checkbox" name="filters" value="@item.Id" id="defaultCheck-@item.Id" @(filters.Contains(item.Id)? "checked":"")>
            <label class="form-check-label" for="defaultCheck-@item.Id">
                @item.Title
            </label>
        </div>
    }
    <button class="btn btn-primary" type="submit">Submit</button>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndtAt)
            </th>
            <th>Categories</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndtAt)
                </td>
                <td>
                    @foreach (var cat in item.Categories)
                    {
                        <span>@cat.Category.Title</span>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>